# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: "*"
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm i
        npm test
  
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Coverage report
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: |
        npm i
        npm run cover
      
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
